[[items]]
name = "Baar Beers"
alternative_names = []
state = "vegan"
description = """
All beers brewed by the Baar AG are vegan.
"""
sources = [
    { type = "url", value = "https://www.swissveg.ch/geklaertegetraenke" }
]
vegan_alternatives = []

[[items]]
name = "Fischerstube Beers"
alternative_names = []
state = "vegan"
description = """
All beers brewed by the Fischerstube AG are vegan.
"""
sources = [
    { type = "url", value = "https://www.swissveg.ch/geklaertegetraenke" }
]
vegan_alternatives = []

[[items]]
name = "Locher Beers"
alternative_names = []
state = "vegan"
description = """
All beers brewed by the Locher AG are vegan.
"""
sources = [
    { type = "url", value = "https://www.swissveg.ch/geklaertegetraenke" }
]
vegan_alternatives = []

[[items]]
name = "Rosengarten Beers"
alternative_names = []
state = "vegan"
description = """
All beers brewed by the Rosengarten AG are vegan.
"""
sources = [
    { type = "url", value = "https://www.swissveg.ch/geklaertegetraenke" }
]
vegan_alternatives = []

[[items]]
name = "Stadtb체hl Beers"
alternative_names = []
state = "vegan"
description = """
All beers brewed by the Stadtb체hl AG are vegan.
"""
sources = [
    { type = "url", value = "https://www.swissveg.ch/geklaertegetraenke" }
]
vegan_alternatives = []

[[items]]
name = "Nilslibr채u"
alternative_names = []
state = "vegan"
description = """
All drinks brewed by Nilslibr채u are vegan.
"""
sources = []
vegan_alternatives = []
