[package]
name = "is-it-vegan"
version = "0.1.0"
authors = ["Jan Nils Ferner <jn_ferner@hotmail.de>"]
edition = "2018"

[dependencies]
url = { version = "1.7.2" }
serde = { version = "1.0", features = ["derive"] }
url_serde = "0.2.0"
elastic = "0.21.0-pre.3"
elastic_derive = "0.21.0-pre.3"
serde_json = "1"
