[[items]]
name = "Curcumin"
alternative_names = [
    "Diferuloylmethane",
    "Curcumin I",
    "C.I. 75300",
    "Natural Yellow 3"
]
e_numbers = ["E100"]
state = "vegan"
description = """
An orange yellow colour derived from the root of the curcuma (turmeric) plant.
Apart from its culinary uses, turmeric is used as a preservative, colorant and flavouring agent in many food products including baked foods, pickles and meat products.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://www.ukfoodguide.net/e100.htm" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Curcumin" }
]
vegan_alternatives = []

[[items]]
name = "Riboflavin"
alternative_names = [
    "Riboflavin-5'-phosphate",
    "FMN", "Lactoflavin",
    "Vactochrome",
    "Vitamin G",
    "Vitamin B2"
]
e_numbers = ["E101", "E101a"]
state = "vegan"
description = """
Riboflavin is yellow or orange-yellow in colour and in addition to being used as a food colouring it is also used to fortify some foods.
It can be found in such foods as baby foods, breakfast cereals, sauces, processed cheese, fruit drinks and vitamin-enriched milk products as well as being widely used in vitamin supplements.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://www.ukfoodguide.net/e101.htm" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Riboflavin" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Flavin_mononucleotide" }
]
vegan_alternatives = []

[[items]]
name = "Tartrazine "
alternative_names = ["FD&C Yellow 5"]
e_numbers = ["E102"]
state = "vegan"
description = """
A synthetic yellow azo dye found in fruit squash, fruit cordial, coloured fizzy drinks, instant puddings, cake mixes, custard powder, soups, sauces, ice cream, ice lollies, sweets, chewing gum, marzipan, jam, jelly, marmalade, mustard, yoghurt and many convenience foods together with glycerine, lemon and honey products. It can also be found in the shells of medicinal capsules.
It can also be used with Brilliant Blue FCF, (E133) to produce various green shades e.g. for tinned processed peas.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Tartrazine" },
    { type = "url", value = "https://www.ukfoodguide.net/e102.htm" }
]
vegan_alternatives = []

[[items]]
name = "Alkannin"
alternative_names = [
    "C.I. Natural red 20",
    "Alkanet extract",
    "Anchusaic acid",
    "Anchusin"
]
e_numbers = ["E103"]
state = "vegan"
description = """
Alkannin is a natural dye that is obtained from the extracts of plants from the borage family Alkanna tinctoria that are found in the south of France.
The dye is used as a food coloring and in cosmetics. It is used as a red-brown food additive in regions such as Australia, but is no longer approved for use.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Alkannin" }
]
vegan_alternatives = []

[[items]]
name = "Quinoline Yellow WS"
alternative_names = [
    "C.I. Acid Yellow 3",
    "Food Yellow 13",
    "D&C Yellow No. 10",
    "Acid yellow 3",
    "Quinidine Yellow KT",
    "Japan Yellow 203",
    "Lemon Yellow ZN 3",
    "C.I. 47005"
]
e_numbers = ["E104"]
state = "vegan"
description = """
A synthetic 'coal tar' dye varying in colour between a dull yellow and greenish-yellow..
Used in lipsticks hair products, colognes; also in a wide range of medications.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Quinoline_Yellow_WS" },
    { type = "url", value = "www.ukfoodguide.net/e104.htm" }
]
vegan_alternatives = []