[[items]]
name = "Wool"
alternative_names = []
state = "carnist"
description = """
Sheep are gentle individuals who, like all animals, feel pain, fear, and loneliness.
But because there’s a market for their fleece and skins, they’re treated as nothing more than wool-producing machines.
In Australia, where more than 50 percent of the world’s merino wool—which is used in products ranging from clothing to carpets—originates,
lambs are forced to endure a gruesome procedure called “mulesing,”
in which huge chunks of skin are cut from the animals’ backsides, often without any painkillers.
"""
sources = [
    { type = "url", value = "https://www.peta.org/issues/animals-used-for-clothing/wool-industry/" }
]
vegan_alternatives = ["Cotton", "Polar Fleece"]

[[items]]
name = "Leather"
alternative_names = []
state = "carnist"
description = """
Leather can be made from cows, pigs, goats, and sheep;
exotic animals such as alligators, ostriches, and kangaroos;
and even dogs and cats, who are slaughtered for their meat and skin in China,
which exports their skins around the world. Because leather is normally not labeled,
you never really know where (or whom) it came from.
In the U.S., many of the millions of cows and other animals who are killed
for their skin endure the horrors of factory farming—extreme crowding and
deprivation as well as castration, branding, tail-docking, and dehorning—all without any painkillers.
At slaughterhouses, animals routinely have their throats cut and some are even skinned and
dismembered while they are still conscious.
Buying leather directly contributes to factory farms and slaughterhouses because skin
is the most economically important coproduct of the meat industry.
Leather is also no friend of the environment, as it shares responsibility for all
the environmental destruction caused by the meat industry as well as the
pollution caused by the toxins used in tanning.
"""
sources = [
    { type = "url", value = "https://www.peta.org/issues/animals-used-for-clothing/leather-industry/" }
]
vegan_alternatives = ["Artificial Leather"]

[[items]]
name = "Isinglass"
alternative_names = []
state = "carnist"
description = """
A collagen used for making jellies, glue and clarifying and fining beer and wine.
The substance is obtained fro dried swim bladders of fish, usually sturgeon or cod.
Needless to say, the fish have to be killed in order to extract their guts.
"""
sources = [
    { type = "url", value = "https://www.craftbrewingbusiness.com/featured/what-is-isinglass-fish-bladders-and-why-is-it-not-vegan-friendly/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Isinglass" }
]
vegan_alternatives = ["Pectin", "Pea Protein"]

[[items]]
name = "Casein"
alternative_names = []
state = "carnist"
description = """
A family of proteins found in dairy milk resposible the strechiness typically associated with melted cheese.
"""
sources = [
    { type = "url", value = "https://www.vegan.com/casein/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Casein" },
    { type = "url", value = "https://itdoesnttastelikechicken.com/melty-stretchy-gooey-vegan-mozarella/" }
]
vegan_alternatives = ["Tapioca Starch"]

[[items]]
name = "Whey"
alternative_names = []
state = "carnist"
description = """
The liquid that remains after dairy milk has been curdled and strained.
A by-product of the cheese industry found in surprisingly many otherwise vegan foods.
Often found in protein shakes.
"""
sources = [
    { type = "url", value = "https://www.vegan.com/whey/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Whey" },
    { type = "url", value = "https://www.bodybuilding.com/fun/10-best-tasting-vegan-protein-powders.html" }
]
vegan_alternatives = ["Pea Protein", "Rice Protein"]
