[[items]]
name = "Curcumin"
alternative_names = [
    "Diferuloylmethane",
    "Curcumin I",
    "C.I. 75300",
    "Natural Yellow 3"
]
e_number = "E100"
state = "vegan"
description = """
An orange yellow colour derived from the root of the curcuma (turmeric) plant.
Apart from its culinary uses, turmeric is used as a preservative, colorant and flavouring agent in many food products including baked foods and pickles.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "http://www.ukfoodguide.net/e100.htm" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Curcumin" }
]
vegan_alternatives = []

[[items]]
name = "Riboflavin"
alternative_names = [
    "FMN",
    "Lactoflavin",
    "Vactochrome",
    "Vitamin G",
    "Vitamin B2"
]
e_number = "E101"
state = "vegan"
description = """
Riboflavin is yellow or orange-yellow in colour and in addition to being used as a food colouring it is also used to fortify some foods.
It can be found in such foods as baby foods, breakfast cereals, sauces, fruit drinks and vitamin-enriched milk products as well as being widely used in vitamin supplements.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "http://www.ukfoodguide.net/e101.htm" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Riboflavin" }
]
vegan_alternatives = []

[[items]]
name = "Riboflavin-5'-phosphate"
alternative_names = [
    "FMN",
    "Lactoflavin",
    "Vactochrome",
    "Vitamin G",
    "Vitamin B2"
]
e_numbers = ["E101a"]
state = "vegan"
description = """
Riboflavin-5'-phosphate is the principal form in which riboflavin is found in cells and tissues.
It requires more energy to produce, but is more soluble than E101 Riboflavin.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "http://www.ukfoodguide.net/e101.htm" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Flavin_mononucleotide" }
]
vegan_alternatives = []

[[items]]
name = "Riboflavin-5-Sodium Phosphate"
alternative_names = [
    "FMN",
    "Lactoflavin",
    "Vactochrome",
    "Vitamin G",
    "Vitamin B2"
]
e_number = "E106"
state = "vegan"
description = """
Riboflavin-5-Sodium Phosphate is a yellow variant of E101a Riboflavin-5'-phosphate
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Flavin_mononucleotide" }
]
vegan_alternatives = []

[[items]]
name = "Tartrazine "
alternative_names = ["FD&C Yellow 5"]
e_number = "E102"
state = "vegan"
description = """
A synthetic yellow azo dye found in fruit squash, fruit cordial, coloured fizzy drinks, instant puddings, cake mixes, custard powder, soups, sauces, ice cream, ice lollies, sweets, chewing gum, marzipan, jam, jelly, marmalade, mustard, yoghurt and many convenience foods together with glycerine and lemon. It can also be found in the shells of medicinal capsules.
It can also be used with Brilliant Blue FCF, (E133) to produce various green shades e.g. for tinned processed peas.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Tartrazine" },
    { type = "url", value = "http://www.ukfoodguide.net/e102.htm" }
]
vegan_alternatives = []

[[items]]
name = "Alkannin"
alternative_names = [
    "C.I. Natural red 20",
    "Alkanet extract",
    "Anchusaic acid",
    "Anchusin"
]
e_number = "E103"
state = "vegan"
description = """
Alkannin is a natural dye that is obtained from the extracts of plants from the borage family Alkanna tinctoria that are found in the south of France.
The dye is used as a food coloring and in cosmetics. It is used as a red-brown food additive in regions such as Australia, but is no longer approved for use.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Alkannin" }
]
vegan_alternatives = []

[[items]]
name = "Quinoline Yellow WS"
alternative_names = [
    "C.I. Acid Yellow 3",
    "Food Yellow 13",
    "D&C Yellow No. 10",
    "Acid yellow 3",
    "Quinidine Yellow KT",
    "Japan Yellow 203",
    "Lemon Yellow ZN 3",
    "C.I. 47005"
]
e_number = "E104"
state = "vegan"
description = """
A synthetic 'coal tar' dye varying in colour between a dull yellow and greenish-yellow..
Used in lipsticks hair products, colognes",
 also in a wide range of medications.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Quinoline_Yellow_WS" },
    { type = "url", value = "http://www.ukfoodguide.net/e104.htm" }
]
vegan_alternatives = []

[[items]]
name = "Fast Yellow AB"
alternative_names = [
    "Fast Yellow",
    "Acid Yellow",
    "Food Yellow 2",
    "C.I. 13015"
]
e_number = "E105"
state = "vegan"
description = """
Fast Yellow AB is an azo dye. It used to be used as a food dye.
It is now delisted in both Europe and USA and is forbidden if used in foods and drinks, as toxicological data has shown it is harmful.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Fast_Yellow_AB" }
]
vegan_alternatives = []

[[items]]
name = "Yellow 2G"
alternative_names = [
    "Lissamine Fast Yellow",
    "C.I. Acid Yellow 17",
    "C.I. 18965",
    "Light Fast Yellow 2G",
    "C.I. Food Yellow 5",
    "Acid Leather Yellow 2GL",
    "Erio Flavine SX",
    "Fenalan Yellow G",
    "Erio Flavine 3G",
    "Kayacyl Yellow GG"
]
e_number = "E107"
state = "vegan"
description = """
Yellow 2G is a food coloring.
It has the appearance of a yellow powder, and it is soluble in water. It is a synthetic yellow azo dye.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Yellow_2G" }
]
vegan_alternatives = []

[[items]]
name = "Sunset Yellow FCF"
alternative_names = [
    "Orange Yellow S",
    "FD&C Yellow 6",
    "C.I. 15985"
]
e_number = "E110"
state = "vegan"
description = """
A synthetic 'coal tar' and azo yellow dye used in fermented foods which must be heat treated.
Found in orange squash, marzipan, Swiss roll, apricot jam, citrus marmalade, lemon curd, sweets, hot chocolate mix and packet soups, breadcrumbs, ice cream, and many medications.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Sunset_Yellow_FCF" },
    { type = "url", value = "http://www.ukfoodguide.net/e110.htm" }
]
vegan_alternatives = []

[[items]]
name = "Orange GGN"
alternative_names = [
    "Alpha-Naphthol Orange"
]
e_number = "E110"
state = "vegan"
description = """
Orange GGN is an azo dye formerly used as a food dye.
In Europe, it has been forbidden for use in foods since 1 January 1978.
It has never been included in the food additives list of the Codex Alimentarius.
As such, it is forbidden for food use in general, because toxicological data has shown it is harmful.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Orange_GGN" }
]
vegan_alternatives = []

[[items]]
name = "Carmine"
alternative_names = [
    "Cochineal",
    "Carminic acid",
    "C.I. Natural Red 4",
    "Crimson Lake",
    "C.I. 75470"    
]
e_number = "E120"
state = "carnist"
description = """
An expensive red colouring extracted from the crushed carcasses of the female Dactylopius coccus, a cactus-feeding scale insect,
which are killed by either immersion in hot water or by exposure to sunlight, steam, or the heat of an oven.
The variety in the appearance of commercial cochineal is caused by these differing extraction methods.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Carmine" },
    { type = "url", value = "http://www.ukfoodguide.net/e120.htm" },
    { type = "url", value = "https://www.vegan.com/carmine/" }

]
vegan_alternatives = ["Beetroot Juice", "Allura Red AC"]

[[items]]
name = "Citrus Red 2"
alternative_names = [
    "Citrus Red No. 2",
    "C.I. Solvent Red 80",
    "C.I. 12156"
]
e_number = "E121"
state = "vegan"
description = """
Citrus Red 2 is an artificial dye.
As a food dye, it has been permitted by the US Food and Drug Administration (FDA) since 1956 to color the skin of oranges.
Citrus Red 2 is listed by the International Agency for Research on Cancer (IARC) as a group 2B carcinogen, a substance "possibly carcinogenic to humans".
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Citrus_Red_2" }

]
vegan_alternatives = []

[[items]]
name = "Azorubine"
alternative_names = [
    "Carmoisine",
    "Food Red 3",
    "Azorubin S",
    "Brillantcarmoisin O",
    "Acid Red 14",
    "C.I. 14720"
]
e_number = "E122"
state = "vegan"
description = """
A synthetic red azo dye used in foods which must be heat treated after fermentation.
Also found in marzipan, Swiss roll, jams and preserves, sweets, brown sauce, flavoured yogurts, packet soups, jellies and breadcrumbs.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "http://www.ukfoodguide.net/e122.htm" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Azorubine" }
]
vegan_alternatives = []

[[items]]
name = "Amaranth"
alternative_names = [
    "FD&C Red No. 2",
    "C.I. Food Red 9",
    "Acid Red 27",
    "Azorubin S",
    "C.I. 16185"
]
e_number = "E123"
state = "vegan"
description = """
Derived from the small herbaceous plant of the same name. 
A purplish-red (blackcurrant) synthetic coal tar or azo dye found in ice creams, gravy granules, jams, jelly, tinned fruit pie fillings, packeted cake mixes and soups.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "http://www.ukfoodguide.net/e123.htm" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Amaranth_(dye)" }
]
vegan_alternatives = []

[[items]]
name = "Ponceau 4R"
alternative_names = [
    "C.I. 16255",
    "Cochineal Red A",
    "C.I. Acid Red 18",
    "Brilliant Scarlet 3R",
    "Brilliant Scarlet 4R",
    "New Coccine"
]
e_number = "E124"
state = "vegan"
description = """
A red synthetic coal tar or azo dye found in dessert toppings, jelly, dressings, tinned strawberries, fruit pie fillings, packeted cake mixes and soups.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "http://www.ukfoodguide.net/e124.htm" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Ponceau_4R" }
]
vegan_alternatives = []

[[items]]
name = "Scarlet GN"
alternative_names = [
    "Crimson 4R",
    "C.I. Food Red 1",
    "Food red 1",
    "FD & C Red no. 4",
    "Hexacol Ponceau SX",
    "Maple Ponceau SX",
    "Ponceau SX",
    "Purple 4R"
]
e_number = "E125"
state = "vegan"
description = """
Scarlet GN is a red azo dye once used as a food dye.
In the United States, it is not permitted for use in food or ingested drugs and may only be used in externally applied drugs and cosmetics.
An exception was added in 1965 to allow the coloring of maraschino cherries, which then were considered mainly decorative and not a foodstuff.
This exception was repealed in 1976 due to mounting evidence over its safety concerns.
In the European Union, it is not permitted as a food additive."""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Scarlet_GN" }
]
vegan_alternatives = []

[[items]]
name = "Ponceau 6R"
alternative_names = [
    "Crystal ponceau 6R",
    "Crystal scarlet",
    "Brilliant crystal scarlet 6R",
    "Acid Red 44",
    "C.I. 16250"
]
e_number = "E126"
state = "vegan"
description = """
Ponceau 6R is a red azo dye. It is soluble in water and slightly soluble in ethanol.
It is closely related to Amaranth (E123).
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Ponceau_6R" }
]
vegan_alternatives = []

[[items]]
name = "Erythrosine"
alternative_names = [
    "Red No. 3",
    "FD&C Red 3"
]
e_number = "E127"
state = "vegan"
description = """
A cherry-pink/red synthetic coal tar dye found in cocktail, glac√© and tinned cherries, canned fruit, sweets, bakery, snack foods, biscuits, chocolate and stuffed olives.
It is also used to reveal plaque in dental disclosing tablets. 
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Erythrosine" },
    { type = "url", value = "http://www.ukfoodguide.net/e127.htm" }
]
vegan_alternatives = []

[[items]]
name = "Red 2G"
alternative_names = [
    "Acid Red 1",
    "Food Red 10",
    "Amidonaphthol red G",
    "Azogeranine",
    "Azophloxine",
    "Azofloxin",
    "C.I. 18050"
]
e_number = "E128"
state = "vegan"
description = """
A red synthetic coal tar or azo dye. Altough Red 2G is vegan, it is primarily used to colour meats.
It can also be found in jams and drinks or as a dye for coatings, inks, paper, crepe paper and fine tissue. 
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Red_2G" },
    { type = "url", value = "http://www.ukfoodguide.net/e128.htm" }
]
vegan_alternatives = []

[[items]]
name = "Allura Red AC"
alternative_names = [
    "Allura Red",
    "Food Red 17",
    "C.I. 16035",
    "FD&C Red 40"
]
e_number = "E129"
state = "vegan"
description = """
Orange-red colour used in sweets, soft drinks, condiments, cotton candy, cherry flavored products, children's medications, cosmetics and tattoo ink.
A red synthetic azo dye introduced in the early eighties to replace Amaranth, E123, in the United States of America where E123 is prohibited.
It is by far the most commonly used red dye in the United States.
"""
sources = [
    { type = "url", value = "https://elated.co.za/which-e-numbers-are-vegan/" },
    { type = "url", value = "https://en.wikipedia.org/wiki/Allura_Red_AC" },
    { type = "url", value = "http://www.ukfoodguide.net/e129.htm" }
]
vegan_alternatives = []
